TARGET := iphone:clang:latest:15.0
ARCHS = arm64 arm64e
THEOS_PACKAGE_SCHEME = rootless
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SwitcherTrace

SwitcherTrace_FILES = Tweak.x
SwitcherTrace_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
SwitcherTrace_FRAMEWORKS = Foundation

include $(THEOS_MAKE_PATH)/tweak.mk
